apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openaipoc-chart.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: 
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "openaipoc-chart.fullname" . }}
            port:
              number: {{ .Values.service.port }}